plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hoshinoriji.miuihomelandscape'
    compileSdk 33

    defaultConfig {
        applicationId 'com.hoshinoriji.miuihomelandscape.vili'
        minSdk 33
        targetSdk 33
        versionCode 50301
        versionName '5.3.1-vili'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
